// Generated by CoffeeScript 1.8.0
this.Point = (function() {
  function Point(x, y) {
    this.x = x;
    this.y = y;
    points.push(this);
    things.push(this);
    this.vx = 0;
    this.vy = 0;
    this.fx = 0;
    this.fy = 0;
    this.gravity = 0.05;
    this.airfriction = 0.01;
    this.friction = 0.7;
  }

  Point.prototype.update = function() {
    this.vx /= this.airfriction + 1;
    this.vy += this.gravity;
    this.x += this.vx += this.fx;
    this.y += this.vy += this.fy;
    this.fx = 0;
    return this.fy = 0;

    /*
    		 * @TODO have constraints collide as well
    		for solid in solids
    			if solid.collision(@x, @y)
    				@y -= @vy+0.1 # @FIXME magic number
    				@vy = -abs(@vy)/5
    				@vx /= (@friction + 1)
    				 * @TODO non-vertical collision with surfaces
     */
  };

  return Point;

})();
